name: C++ CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure
        run: cmake --preset debug
      - name: Build
        run: cmake --build --preset debug
      - name: Test
        run: ctest --preset debug
